### ISSUE TITLE
Adding an optional parameter for servo motor mount angle in inverse kinematics method of KinematicsSolver class

### ISSUE THREAD

**Issue by VisteK528** [HexapodBionik/MotionPlanning#14]
# Things to be done:
- [x] Implementation of additional parameters mentioned in the title of the issue for the constructor of the `KinematicsSolver` class
- [x] Adding the offset for each joint in `inverse_kinematics` method according to the values of newly added arguments
- [x] Update all the unit tests of the  `kinematics` subpackage according to the changes in previous sections 
- [x] Add new unit tests for forward and inverse kinematics for new leg models (the ones containing bends in link 3 and optionally link 2)

**Comment by dbarania** [comment]
Jeśli argument dotyczący mount_angle jest opcjonalny, to czy faktycznie muszę edytować te testy? Przecież to jest jakby wszystkie kąty były równe zero. Wystarczy bym dorobił więcej testów by sprawdzić czy wszystko się zgadza

**Comment by dbarania** [comment]
@VisteK528 Wydaje mi się, że skończone, co teraz? czekać aż janek skończy bawić się strukturą?

**Comment by VisteK528** [comment]
Generalnie otwieramy pull request i czekamy na testy w wizualizacji i na fizycznym modelu

**Comment by dbarania** [comment]
Direction of project went in other direction and this solution ended up pointless
