### ISSUE TITLE
Naprawa testów po zmianach w strukturze projektu

### ISSUE THREAD

**Issue by dbarania** [HexapodBionik/MotionPlanning#5]
Po ostatnich zmianach w strukturze tego projektu testy przestały działać, należy poprawić nazwy oraz ścieżki testowe

**Comment by barszot** [comment]
Utworzyłem gałąź UnitTestsOfKinematicsSolvers i dodałem tam pierwszy plik testowy. W ciągu następnego tygodnia dodam tam też parę kolejnych.
