### ISSUE TITLE
Inverse solver fails for some input data

### ISSUE THREAD

**Issue by VisteK528** [HexapodBionik/MotionPlanning#8]
The inverse method of KinematicsSolver from kinematics package fails after being called on input data if x or y coordinate value of desired position is equal to length of a1 link.

For myself the error occured, while operating with this configuration:
```python
mount_t = np.array([0, 0, 0.05])
t1 = np.array([0.05, 0, 0])
t2 = np.array([0.09, 0, 0])
t3 = np.array([0.1, 0, 0])


kinematics_solver = KinematicsSolver(mount_t, t1, t2, t3)
```

And the destination point was:
```python
p = np.array([0, -0.05, 0])
q = kinematics_solver.inverse(p)
```

Then the solver returned ```q=[90 nan nan]```

**Comment by antoniprzybylik** [comment]
Odkryłem, że testy były niepoprawnie ponumerowane i test_5 się nie uruchamiał (https://github.com/HexapodBionik/MotionPlanning/commit/17d62501ec56abee30e79ea196e45e7eb649e6c3). Po naprawieniu tego, okazało się, że ten test nie przechodzi. Należy to naprawić.

Dodatkowo należy naprawić warningi. Wiem, że numpy dopuszcza dzielenie przez zero (i zwraca wtedy inf), a przy dzieleniu 0./0. zwraca NaN, więc obecny kod działa, ale:
1. Nie wiemy, czy to zachowanie nie zmieni się w przyszłych wersjach numpy.
2. Bardziej elegancko jest wyifować corner-case'y niż cieszyć się, że w danym przypadku Undefined Beahviour numpy zachowuje się tak jak chcemy.
